version: 2
jobs:
  build:
    macos:
      xcode: "8.3.3"
    steps:
      - checkout
      - run: ls
      - run: chmod a+x ./install.sh
      - run: chmod a+x ./build.sh
      - run: ./install.sh
      - run: ./build.sh